/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_1 (
    input [5:0] alufn,
    input [15:0] inputStringA,
    input [15:0] inputStringB,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  wire [16-1:0] M_adderUnit_out;
  wire [1-1:0] M_adderUnit_cout;
  wire [1-1:0] M_adderUnit_z;
  wire [1-1:0] M_adderUnit_v;
  wire [1-1:0] M_adderUnit_n;
  reg [16-1:0] M_adderUnit_a;
  reg [16-1:0] M_adderUnit_b;
  reg [6-1:0] M_adderUnit_alufn;
  adder_5 adderUnit (
    .a(M_adderUnit_a),
    .b(M_adderUnit_b),
    .alufn(M_adderUnit_alufn),
    .out(M_adderUnit_out),
    .cout(M_adderUnit_cout),
    .z(M_adderUnit_z),
    .v(M_adderUnit_v),
    .n(M_adderUnit_n)
  );
  
  wire [16-1:0] M_booleanUnit_out;
  reg [16-1:0] M_booleanUnit_a;
  reg [16-1:0] M_booleanUnit_b;
  reg [6-1:0] M_booleanUnit_alufn;
  boolean_6 booleanUnit (
    .a(M_booleanUnit_a),
    .b(M_booleanUnit_b),
    .alufn(M_booleanUnit_alufn),
    .out(M_booleanUnit_out)
  );
  
  wire [16-1:0] M_shifterUnit_out;
  reg [16-1:0] M_shifterUnit_a;
  reg [4-1:0] M_shifterUnit_b;
  reg [6-1:0] M_shifterUnit_alufn;
  shifter_7 shifterUnit (
    .a(M_shifterUnit_a),
    .b(M_shifterUnit_b),
    .alufn(M_shifterUnit_alufn),
    .out(M_shifterUnit_out)
  );
  
  wire [16-1:0] M_compareUnit_out;
  reg [1-1:0] M_compareUnit_z;
  reg [1-1:0] M_compareUnit_v;
  reg [1-1:0] M_compareUnit_n;
  reg [6-1:0] M_compareUnit_alufn;
  compare_8 compareUnit (
    .z(M_compareUnit_z),
    .v(M_compareUnit_v),
    .n(M_compareUnit_n),
    .alufn(M_compareUnit_alufn),
    .out(M_compareUnit_out)
  );
  
  reg z_sig;
  
  reg v_sig;
  
  reg n_sig;
  
  always @* begin
    M_adderUnit_a = inputStringA;
    M_adderUnit_b = inputStringB;
    M_adderUnit_alufn = alufn;
    z_sig = M_adderUnit_z;
    v_sig = M_adderUnit_v;
    n_sig = M_adderUnit_n;
    z = z_sig;
    v = v_sig;
    n = n_sig;
    M_booleanUnit_a = inputStringA;
    M_booleanUnit_b = inputStringB;
    M_booleanUnit_alufn = alufn;
    M_shifterUnit_a = inputStringA;
    M_shifterUnit_b = inputStringB;
    M_shifterUnit_alufn = alufn;
    M_compareUnit_v = v_sig;
    M_compareUnit_n = n_sig;
    M_compareUnit_z = z_sig;
    M_compareUnit_alufn = alufn;
    
    case (alufn[4+1-:2])
      default: begin
        out = M_adderUnit_out;
      end
      2'h2: begin
        out = M_shifterUnit_out;
      end
      2'h1: begin
        out = M_booleanUnit_out;
      end
      2'h3: begin
        out = M_compareUnit_out;
      end
    endcase
  end
endmodule
